name: 'Tests: Cypress e2e'

on:
  push:
    branches: [ "main", "cypress-gh-action" ] # TODO remove after checking it works
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '45 15 * * 4'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install yarn dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0
        with:
          project: ./web
          build: cd web; yarn build
          start: cd web; yarn start
